  std::string get_crypto_loan_borrowable_coins(const QueryParams& filters = {});
  std::string get_crypto_loan_collateral_coins(const QueryParams& filters = {});
  std::string get_crypto_loan_max_collateral_reduction(const QueryParams& filters);
  std::string adjust_crypto_loan_collateral(const std::string& json_body);
  std::string get_crypto_loan_collateral_adjustment_history(const QueryParams& filters = {});
  std::string get_crypto_loan_position();
  std::string get_crypto_loan_max_loan_amount(const std::string& json_body);
  std::string borrow_flexible_crypto_loan(const std::string& json_body);
  std::string repay_flexible_crypto_loan(const std::string& json_body);
  std::string repay_flexible_crypto_loan_with_collateral(const std::string& json_body);
  std::string get_flexible_crypto_loans(const QueryParams& filters = {});
  std::string get_flexible_crypto_loan_borrow_history(const QueryParams& filters = {});
  std::string get_flexible_crypto_loan_repayment_history(const QueryParams& filters = {});
  std::string get_fixed_crypto_loan_lending_market(const QueryParams& filters);
  std::string get_fixed_crypto_loan_borrowing_market(const QueryParams& filters);
  std::string borrow_fixed_crypto_loan(const std::string& json_body);
  std::string renew_fixed_crypto_loan(const std::string& json_body);
  std::string supply_fixed_crypto_loan(const std::string& json_body);
  std::string cancel_fixed_crypto_loan_borrow_order(const std::string& json_body);
  std::string cancel_fixed_crypto_loan_supply_order(const std::string& json_body);
  std::string get_fixed_crypto_loan_borrow_contract_info(const QueryParams& filters = {});
  std::string get_fixed_crypto_loan_supply_contract_info(const QueryParams& filters = {});
  std::string get_fixed_crypto_loan_borrow_order_info(const QueryParams& filters = {});
  std::string get_fixed_crypto_loan_renew_order_info(const QueryParams& filters = {});
  std::string get_fixed_crypto_loan_supply_order_info(const QueryParams& filters = {});
  std::string repay_fixed_crypto_loan(const std::string& json_body);
  std::string repay_fixed_crypto_loan_with_collateral(const std::string& json_body);
  std::string get_fixed_crypto_loan_repayment_history(const QueryParams& filters = {});
  std::string get_legacy_crypto_loan_borrowable_coins(const QueryParams& filters = {});
  std::string get_legacy_crypto_loan_collateral_coins(const QueryParams& filters = {});
  std::string get_legacy_crypto_loan_account_limits(const QueryParams& filters);
  std::string borrow_legacy_crypto_loan(const std::string& json_body);
  std::string repay_legacy_crypto_loan(const std::string& json_body);
  std::string get_legacy_crypto_loan_unpaid_loans(const QueryParams& filters = {});
  std::string get_legacy_crypto_loan_repayment_history(const QueryParams& filters = {});
  std::string get_legacy_crypto_loan_completed_history(const QueryParams& filters = {});
  std::string get_legacy_crypto_loan_max_collateral_reduction(const QueryParams& filters);
  std::string adjust_legacy_crypto_loan_collateral(const std::string& json_body);
  std::string get_legacy_crypto_loan_ltv_adjustment_history(const QueryParams& filters = {});
