if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
    set(BYBIT_BUILD_TESTS_DEFAULT ON)
else()
    set(BYBIT_BUILD_TESTS_DEFAULT OFF)
endif()
option(BYBIT_BUILD_TESTS "Build tests" ${BYBIT_BUILD_TESTS_DEFAULT})
option(BYBIT_BUILD_NETWORK_TESTS "Build tests that call live Bybit endpoints" OFF)

if(NOT BYBIT_BUILD_TESTS)
    return()
endif()

include(CTest)
if(NOT BUILD_TESTING)
    return()
endif()

function(bybit_add_test target source)
    add_executable(${target} ${source})
    target_link_libraries(${target} PRIVATE bybit_client)
    add_test(NAME ${target} COMMAND ${target})
endfunction()

if(BYBIT_BUILD_NETWORK_TESTS)
    bybit_add_test(bybit_public_test tests/test_public.cpp)
endif()

bybit_add_test(bybit_signing_test tests/test_signing.cpp)
bybit_add_test(bybit_http_options_test tests/test_http_options.cpp)
bybit_add_test(bybit_market_api_test tests/test_market_api.cpp)
bybit_add_test(bybit_account_api_test tests/test_account_api.cpp)
bybit_add_test(bybit_advanced_earn_api_test tests/test_advanced_earn_api.cpp)
bybit_add_test(bybit_affiliate_api_test tests/test_affiliate_api.cpp)
bybit_add_test(bybit_broker_api_test tests/test_broker_api.cpp)
bybit_add_test(bybit_card_api_test tests/test_card_api.cpp)
bybit_add_test(bybit_crypto_loan_api_test tests/test_crypto_loan_api.cpp)
bybit_add_test(bybit_earn_api_test tests/test_earn_api.cpp)
bybit_add_test(bybit_institutional_loan_api_test tests/test_institutional_loan_api.cpp)
bybit_add_test(bybit_pre_upgrade_api_test tests/test_pre_upgrade_api.cpp)
bybit_add_test(bybit_rfq_api_test tests/test_rfq_api.cpp)
bybit_add_test(bybit_spot_margin_api_test tests/test_spot_margin_api.cpp)
bybit_add_test(bybit_spread_api_test tests/test_spread_api.cpp)
bybit_add_test(bybit_strategy_api_test tests/test_strategy_api.cpp)
bybit_add_test(bybit_web3_api_test tests/test_web3_api.cpp)
bybit_add_test(bybit_asset_api_test tests/test_asset_api.cpp)
bybit_add_test(bybit_leverage_token_api_test tests/test_leverage_token_api.cpp)
bybit_add_test(bybit_websocket_api_test tests/test_websocket_api.cpp)
bybit_add_test(bybit_sbe_market_decoder_test tests/test_sbe_market_decoder.cpp)
bybit_add_test(bybit_sbe_order_entry_encoder_test tests/test_sbe_order_entry_encoder.cpp)
bybit_add_test(bybit_sbe_order_entry_batch_test tests/test_sbe_order_entry_batch.cpp)
bybit_add_test(bybit_websocket_lifecycle_test tests/test_websocket_lifecycle.cpp)
bybit_add_test(bybit_websocket_messages_test tests/test_websocket_messages.cpp)
if(BYBIT_ENABLE_WEBSOCKET)
    bybit_add_test(bybit_websocket_callback_connect_race_test tests/test_websocket_callback_connect_race.cpp)
    bybit_add_test(bybit_websocket_close_race_test tests/test_websocket_close_race.cpp)
    bybit_add_test(bybit_websocket_self_destruction_test tests/test_websocket_self_destruction.cpp)
    set_tests_properties(bybit_websocket_callback_connect_race_test bybit_websocket_close_race_test
        bybit_websocket_self_destruction_test
        PROPERTIES TIMEOUT 10)
endif()

if(NOT WIN32)
    # The local request-capture harness uses POSIX sockets.
    bybit_add_test(bybit_rest_request_contracts_test tests/test_rest_request_contracts.cpp)
endif()
